### ISSUE TITLE
[Fixed] see comment/ No such interface  'wlan' -- in module (inet::HostAutoConfigurator) ERROR while running car example

### ISSUE THREAD

**Issue by DingZY22** [inet-framework/simulte#58] opened 2021-01-29 23:17 UTC
Does anyone meet the same error with versions:

OMNET++ 5.6.2
INET 4.2.2
SimuLTE 1.2.0
Veins 5.1
sumo 1.8.0

I don't change the original configuration of the network..

**Comment by wischhof** [comment] 2021-01-30 13:49
This is a known problem with the HostAutoConfigurator, a fix is already available: see pull request #57 

Until the pull request is merged, you can manually change the files mentioned within the pull request or you can simply clone [https://github.com/roVer-HM/simulte/tree/v1.2.0_fix_cars](https://github.com/roVer-HM/simulte/tree/v1.2.0_fix_cars) 

(this issue is a duplicate of #55)

**Comment by DingZY22** [comment] 2021-01-30 15:21
> This is a known problem with the HostAutoConfigurator, a fix is already available: see pull request #57
> 
> Until the pull request is merged, you can manually change the files mentioned within the pull request or you can simply clone https://github.com/roVer-HM/simulte/tree/v1.2.0_fix_cars
> 
> (this issue is a duplicate of #55)

------
Thank you!!  It is fixed

**Closed** 2021-02-04 16:32 UTC
